# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'newsapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for newsapp
 
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  target 'newsappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
