# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newsapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newsapp

  target 'newsapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'newsappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'newsapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for newsapp-tvOS

  target 'newsapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
